### ISSUE TITLE
Fix the requirements

### ISSUE THREAD

**Issue by haz** [AI-Planning/api-tools#17]
Both in the domain PDDL and in the tags for the API. Many domains get their tags wrong (strips and typing being two common ones).

- [x] write a script that will allow the pddl project to check a domain PDDL
- [x] run it on the benchmark repo
- [x] write a script to cross reference the requirements listed and tagged requirements
- [x] update all of the incorrect tags

**Comment by baonny** [comment]
Created script that will allow pddl project to check a domain PDDL but due to system requirements won't be able to use VAL to check and cross reference requirements (pull-request using planning_domain_capstone branch)
