### ISSUE TITLE
GET request for `/classical/plan/{id}` with invalid id returns 503 error

### ISSUE THREAD

**Issue by Rowan441** [AI-Planning/api-tools#19]
### **Problem:**

hitting api endpoint to lookup an non-existent plan e.g: `https://api.planning.domains/json/classical/plan/123451` returns a 503 error

### **Expected behaviour:**

returns 200 code and

```json
{
   "error": true,
   "message": "No model with id 123451"
}
```

**Comment by haz** [comment]
Solved server-side.
