### ISSUE TITLE
Generalize the PD api file to different formalisms

### ISSUE THREAD

**Issue by haz** [AI-Planning/api-tools#29]
We will soon have more than just `classical` (e.g., `rddl`).

**Comment by eranhirs** [comment]
The [documentation](https://api.planning.domains/) does not mention that we should provide a formalism. However, all the methods require formalism as a parameter. It seems the only formalism at this point is `classical`, and the only place I found it documented is in this issue. I suggest fixing the documentation. Thanks!

**Comment by haz** [comment]
Thanks, @eranhirs ! Which documentation are you referring to? What's at https://api.planning.domains/ ?

**Comment by eranhirs** [comment]
I am confused, is [https://api.planning.domains/](https://api.planning.domains/) not the documentation for this repo? The README file of this repo links there.

**Comment by haz** [comment]
Just wanted to confirm. You might consider the API site as the documentation, or the README here, or the docs on the python implementation, or the command-line output, or ...

**Comment by eranhirs** [comment]
I will clarify. I would like to point out for future users of this API, that it was difficult to find the key "classical".

The website, currently includes the following example:
```
api.get_domains(12)
```
This throws the error
```
>>> get_domains(12)                       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_domains() missing 1 required positional argument: 'formalism'
```

To make it work, you need to write 
```
api.get_domains(12, formalism='classical')
```

**Comment by haz** [comment]
Ah, I see. On the website itself there is documentation for 4 things (REST, python lib, js lib, CLI). I'll file an issue to get all 4 of them cross-referenced with the new era of API usage (in the process of switching over due to the new hosting situation and expansion to other formalisms). Thanks!

**Comment by haz** [comment]
In case you'd like to follow along...

https://github.com/AI-Planning/api-tools/issues/35
