### ISSUE TITLE
Plan from a local file with an API call

### ISSUE THREAD

**Issue by llumfp** [AI-Planning/api-tools#36]
I don't know how can I plan a problem if I have the files in my local computer. I would like to do it with a python script. How can I follow the code?

domain_file = "pddl/domain.pddl"
problem_file = "pddl/problem.pddl"

with open(domain_file, 'r') as file:
    domain_content = file.read()
with open(problem_file, 'r') as file:
    problem_content = file.read()

url = "https://solver.planning.domains"

**Comment by haz** [comment]
This isn't exactly an api-tools issue (as planner solving isn't part of this package), but you can find the API over at https://github.com/AI-Planning/planning-as-a-service?tab=readme-ov-file#example-use

Just replace the localhost stuff with the solver URL (keep the port set to 5001).
